### ISSUE TITLE
Intelligent Auto Completion[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tomlin7** [lucasstarsz/FXPad#4]
**Describe the solution you'd like**
Add autocompletion feature to FXpad.
on `Tab` press, do the completion

**Additional context**
![image](https://user-images.githubusercontent.com/70792552/102977267-c1f50200-4528-11eb-99ca-11834dbb9b67.png)

**Comment by lucasstarsz** [comment]
FXPad is a text editor first. While this would be an interesting feature to add, it likely won't be considered for a long time. As such, I'll have to close it for now. If we reach that point where FXPad becomes more of a code editor, we may revisit this.
