### ISSUE TITLE
ToolTips on hovering over Code[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tomlin7** [lucasstarsz/FXPad#5]
**Describe the solution you'd like**
On mouse hover, display tooltip for the code blocks.

**Describe alternatives you've considered**
show tooltips when the cursor is on the code block

**Additional context**
![image](https://user-images.githubusercontent.com/70792552/102977546-244e0280-4529-11eb-864e-eb2574bbf011.png)

**Comment by lucasstarsz** [comment]
See issue #4.
