### ISSUE TITLE
Errors & warnings Indicator and counter [FEATURE REQUEST]

### ISSUE THREAD

**Issue by tomlin7** [lucasstarsz/FXPad#6]
**Describe the solution you'd like**
add an errors & warnings counter
![image](https://user-images.githubusercontent.com/70792552/102977752-74c56000-4529-11eb-8033-922c6a678209.png)
When there is an error or warning in code indicate it on the side bar or nearby to the scrollbar
![image](https://user-images.githubusercontent.com/70792552/102977896-a63e2b80-4529-11eb-9420-95d8cd3920db.png)

**Comment by lucasstarsz** [comment]
See issue #4.
