### ISSUE TITLE
Code lens[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tomlin7** [lucasstarsz/FXPad#7]
**Describe the solution you'd like**
when hovering over the scroll bar, show the code in relative position, magnified, in a tooltip window

**Additional context**
![image](https://user-images.githubusercontent.com/70792552/102978109-01701e00-452a-11eb-90ca-6df4fdd8ff70.png)

**Comment by lucasstarsz** [comment]
See issue #4.
